test_that("purpose editing preserves boundary and evidence across revisions", {
  store <- local_study_store(withr::local_tempdir())
  a <- store$create("Study", "First question")
  b <- store$save_boundary(a$key, drawn_boundary(draw_fixture()), a$path)
  hash <- tools::md5sum(b$path)
  c <- store$set_purpose(b$key, " Updated question ", b$path)
  expect_identical(c$purpose, "Updated question")
  expect_identical(c$notes, b$notes)
  expect_identical(sf::st_geometry(c$boundary_sf), sf::st_geometry(b$boundary_sf))
  expect_identical(c$study_id, b$study_id)
  expect_identical(tools::md5sum(b$path), hash)
  expect_identical(store$read(c$key), c)
  expect_error(store$set_purpose(b$key, "Stale", b$path), "newer revision")
  d <- store$set_purpose(c$key, "", c$path)
  expect_true(is.na(d$purpose))
  expect_identical(d$notes, b$notes)
  expect_identical(store$set_purpose(d$key, "", d$path), d)
})

test_that("older app drafts use only original purpose notes as fallback", {
  root <- withr::local_tempdir(); key <- paste(rep("a", 32), collapse = "")
  dir.create(file.path(root, key))
  a <- file.path(root, key, "study.gpkg")
  b <- file.path(root, key, "revision-000001.gpkg")
  fluvgeo::start_study_context(a, "Old draft", analyst_notes = "Original question")
  fluvgeo::revise_study_context(a, b, add_note = "Boundary source evidence")
  store <- local_study_store(root)
  old <- store$read(key)
  expect_identical(old$purpose, "Original question")
  revised <- store$set_purpose(key, "New question", old$path)
  expect_identical(revised$purpose, "New question")
  expect_identical(revised$notes, old$notes)
})

test_that("Purpose dialog saves explicitly and escapes current text", {
  store <- local_study_store(withr::local_tempdir())
  shiny::testServer(mod_study_server, args = list(store = store), {
    session$flushReact()
    session$setInputs(name = "Study", notes = "First", create = 1)
    session$setInputs(edit_purpose = 1)
    session$setInputs(new_purpose = "<b>Revised</b>")
    expect_identical(current()$purpose, "First")
    session$setInputs(save_purpose = 1)
    expect_identical(current()$purpose, "<b>Revised</b>")
    expect_match(output$summary$html, "&lt;b&gt;Revised", fixed = TRUE)
    expect_null(purpose_target())
    session$setInputs(edit_purpose = 2, new_purpose = "", save_purpose = 2)
    expect_true(is.na(current()$purpose))
  })
})
