test_that("a named draft is durable and does not invent hierarchy", {
  root <- withr::local_tempdir()
  store <- local_study_store(root)
  draft <- store$create("  Cole <Creek>  ", "  Compare surveys\nwith the customer.  ")
  expect_identical(draft$name, "Cole <Creek>")
  expect_identical(draft$purpose, "Compare surveys\nwith the customer.")
  expect_true(file.exists(draft$path))
  expect_false(draft$boundary)
  expect_identical(c(draft$streams, draft$reaches, draft$events), c(0L, 0L, 0L))
  expect_identical(local_study_store(root)$read(draft$key), draft)
  expect_identical(unname(store$catalog()$choices), draft$key)
  expect_length(store$catalog()$choices, 1)
  before <- tools::md5sum(draft$path)
  another <- store$create("Cole <Creek>")
  expect_false(identical(another$study_id, draft$study_id))
  expect_true(is.na(another$notes))
  expect_identical(tools::md5sum(draft$path), before)
})

test_that("invalid inputs cannot escape storage or create drafts", {
  root <- withr::local_tempdir()
  store <- local_study_store(root)
  for (name in list("", "   ", NA_character_, 2, c("A", "B")))
    expect_error(store$create(name), "Study Area name")
  expect_length(list.files(root), 0)
  for (key in c("../escape", "C:/outside", "abc", ""))
    expect_error(store$read(key), "Choose a saved")
  expect_error(local_study_store(NA_character_), "directory")
  expect_error(store$create("A", NA_character_), "Purpose")
})

test_that("unreadable saved studies are retained and counted", {
  root <- withr::local_tempdir()
  bad <- file.path(root, paste(rep("a", 32), collapse = ""))
  dir.create(bad)
  store <- local_study_store(root)
  expect_identical(store$catalog()$unreadable, 1L)
  expect_length(store$catalog()$choices, 0)
  expect_true(dir.exists(bad))
})
