test_that("drawing conversion retains coordinates and rejects unsafe geometry", {
  x <- drawn_boundary(draw_fixture())
  expect_s3_class(x, "sf")
  expect_equal(sf::st_crs(x)$epsg, 4326)
  expect_equal(unname(sf::st_coordinates(x)[1, 1:2]), c(-96, 41))
  expect_error(drawn_boundary(NULL), "Draw one")
  empty <- draw_fixture(); empty$features <- list()
  expect_error(drawn_boundary(empty), "Draw one")
  two <- draw_fixture(); two$features <- rep(two$features, 2)
  expect_error(drawn_boundary(two), "Draw one")
  point <- draw_fixture(); point$features[[1]]$geometry$type <- "Point"
  expect_error(drawn_boundary(point), "polygon")
  expect_error(drawn_boundary(draw_fixture(list(c(0, 0), c(1, 1), c(0, 1), c(1, 0), c(0, 0)))), "invalid")
  expect_error(drawn_boundary(draw_fixture(list(c(0, 0), c(1, 0), c(1, 1), c(0, 1)))), "Finish")
  expect_error(drawn_boundary(draw_fixture(list(c(500, 0), c(1, 0), c(1, 1), c(500, 0)))), "invalid")
})

test_that("boundary revisions preserve study identity, original and geometry", {
  root <- withr::local_tempdir()
  store <- local_study_store(root)
  original <- store$create("Study", "Customer intent")
  hash <- tools::md5sum(original$path)
  shape <- drawn_boundary(draw_fixture())
  saved <- store$save_boundary(original$key, shape, original$path)
  expect_true(saved$boundary)
  expect_identical(saved$study_id, original$study_id)
  expect_identical(tools::md5sum(original$path), hash)
  expect_match(saved$purpose, "Customer intent", fixed = TRUE)
  expect_match(saved$notes, "Drawn and explicitly saved", fixed = TRUE)
  expect_identical(sf::st_as_binary(sf::st_geometry(saved$boundary_sf)), sf::st_as_binary(sf::st_geometry(shape)))
  expect_equal(sf::st_crs(saved$boundary_sf)$epsg, 4326)
  expect_identical(local_study_store(root)$read(saved$key), saved)
  expect_length(store$catalog()$choices, 1)
  expect_error(store$save_boundary(original$key, shape, original$path), "newer revision")
  before <- tools::md5sum(saved$path)
  next_saved <- store$save_boundary(saved$key, shape, saved$path)
  expect_identical(next_saved$study_id, saved$study_id)
  expect_identical(tools::md5sum(saved$path), before)
  expect_error(store$save_boundary(saved$key, sf::st_sf(x = 1, geometry = sf::st_sfc(sf::st_point(c(0, 0)), crs = 4326)), next_saved$path), "POLYGON")
  expect_identical(store$read(saved$key)$path, next_saved$path)
})

test_that("editor waits for explicit save and clears unfinished candidates", {
  store <- local_study_store(withr::local_tempdir())
  study <- store$create("Study")
  result <- NULL
  state <- new.env(parent = emptyenv()); state$active <- TRUE
  shiny::testServer(mod_boundary_server, args = list(study = study, store = store,
    is_active = function() state$active, on_saved = function(x) result <<- x), {
    session$flushReact()
    expect_match(output$map, "addDrawToolbar", fixed = TRUE)
    session$setInputs(map_draw_all_features = draw_fixture())
    expect_s3_class(candidate(), "sf")
    expect_false(store$read(study$key)$boundary)
    session$setInputs(map_draw_editstart = TRUE)
    expect_null(candidate())
    session$setInputs(save = 1)
    expect_null(result)
    session$setInputs(map_draw_all_features = draw_fixture())
    empty <- list(type = "FeatureCollection", features = list())
    session$setInputs(map_draw_all_features = empty)
    expect_null(candidate())
    session$setInputs(save = 2)
    expect_null(result)
    session$setInputs(map_draw_all_features = draw_fixture())
    state$active <- FALSE
    session$setInputs(save = 3)
    expect_null(result)
    state$active <- TRUE
    session$setInputs(save = 4)
    expect_true(result$boundary)
    expect_null(candidate())
    expect_identical(result$study_id, study$study_id)
  })
})

test_that("switching study destroys the earlier editor and preserves identity", {
  store <- local_study_store(withr::local_tempdir())
  first <- store$create("First")
  second <- store$create("Second")
  shiny::testServer(mod_study_server, args = list(store = store), {
    session$flushReact()
    session$setInputs(saved = first$key, open = 1)
    first_editor <- output$boundary_editor$html
    session$setInputs(saved = second$key, open = 2)
    expect_false(identical(output$boundary_editor$html, first_editor))
    expect_identical(current()$key, second$key)
    session$setInputs(another = 1)
    expect_null(current())
  })
})
