test_that('Reach DEM requests use saved grid, mask, sources and vertical target', {
 fixture<-Sys.getenv('FGSTUDIO_REAL_MOSAIC_RESULT')
 skip_if(!nzchar(fixture),'Provide the existing real Reach fixture')
 t<-readRDS(fixture);s<-local_study_store(dirname(dirname(t$context_path)));x<-s$read(t$key)
 g<-s$acquisition_groups(t$key)$groups[[t$group_id]]
 ctx<-list(group_id=t$group_id,group_path=g$path,path=x$path,
   streams=x$stream_inventory[x$stream_inventory$stream_id %in% g$streams$stream_id,])
 full<-terrain_dem_request(s,x,ctx,t$reach$reach_id)
 expect_identical(full$scope,'reach')
 expect_identical(full$source_extent,as.vector(terra::ext(terra::rast(full$mask_file))))
 expect_identical(full$mask_file,t$mask_original)
 expect_identical(full$sources,unique(full$source_selection$path))
 expect_identical(full$target_vertical,x$vertical_reference)
 expect_null(full$result)
 small<-terrain_dem_request(s,x,ctx,t$reach$reach_id,as.vector(terra::ext(terra::rast(t$result$path))))
 expect_identical(small$scope,'reach_portion')
 expect_false(identical(terrain_dem_trial_recipe(full),terrain_dem_trial_recipe(small)))
 expect_null(terrain_dem_request(s,x,NULL,t$reach$reach_id))
 stream<-terrain_dem_request(s,x,ctx,stream_id=t$reach$stream_id)
 expect_identical(stream$scope,'stream')
 expect_identical(stream$level,'Stream')
 expect_null(stream$reach)
 expect_identical(stream$boundary$stream_id,t$reach$stream_id)
 expect_identical(stream$source_extent,as.vector(terra::ext(terra::rast(stream$mask_file))))
 expect_false(identical(stream$mask_file,full$mask_file))
 expect_false(identical(terrain_dem_trial_recipe(stream),terrain_dem_trial_recipe(full)))
 expect_error(terrain_dem_request(s,x,ctx,t$reach$reach_id,stream_id=t$reach$stream_id),'one Reach or Stream')
 expect_error(terrain_dem_request(s,x,ctx,'missing'),'not in this Study')
 x$vertical_reference$crs_authority<-'EPSG:5703'
 expect_error(terrain_dem_request(s,x,ctx,t$reach$reach_id),'Review CRS')
})
