test_that("renaming retains identity, boundary, notes, originals and catalog", {
  store <- local_study_store(withr::local_tempdir())
  draft <- store$create("Original", "Customer question")
  x <- store$save_boundary(draft$key, drawn_boundary(draw_fixture()), draft$path)
  hash <- tools::md5sum(x$path)
  y <- store$rename(x$key, " Revised name ", x$path)
  expect_identical(y$name, "Revised name")
  expect_identical(y$study_id, x$study_id)
  expect_identical(y$notes, x$notes)
  expect_identical(sf::st_as_binary(sf::st_geometry(y$boundary_sf)),
    sf::st_as_binary(sf::st_geometry(x$boundary_sf)))
  expect_identical(sf::st_crs(y$boundary_sf), sf::st_crs(x$boundary_sf))
  expect_identical(tools::md5sum(x$path), hash)
  expect_identical(store$read(y$key), y)
  expect_match(names(store$catalog()$choices), "Revised name", fixed = TRUE)
  expect_identical(store$rename(y$key, y$name, y$path), y)
  expect_error(store$rename(x$key, "Stale", x$path), "newer revision")
  expect_error(store$rename(y$key, " ", y$path), "Enter")
})

test_that("name form validates and refreshes the saved study", {
  store <- local_study_store(withr::local_tempdir())
  shiny::testServer(mod_study_server, args = list(store = store), {
    session$flushReact()
    session$setInputs(name = "First", create = 1)
    original <- current()
    session$setInputs(edit_name = 1)
    session$setInputs(new_name = " ", save_name = 1)
    expect_match(rename_error(), "Enter")
    expect_identical(current(), original)
    session$setInputs(new_name = "Updated", save_name = 2)
    expect_identical(current()$name, "Updated")
    expect_identical(current()$study_id, original$study_id)
    expect_match(names(catalog_state()$choices), "Updated")
    expect_null(rename_target())
    session$setInputs(workspace_task = "new", save_name = 3)
    expect_null(current())
  })
})
