test_that("completed hydro results reopen and stale jobs cannot publish",{
  d <- withr::local_tempdir();context <- file.path(d,"study.gpkg");file.create(context)
  store <- study_hydro_store(function(key) context)
  lines <- hydro_drawn_lines(list(type="FeatureCollection",features=list(list(
    geometry=list(type="LineString",coordinates=list(c(-93,40),c(-93.001,40.001)))))))
  rec <- store$hydro_save("study","event","stream","dem1",lines,NULL,context)
  job <- store$hydro_prepare(rec);output <- file.path(job,"hydro-dem.tif");writeBin(as.raw(1:9),output)
  result <- store$hydro_publish(rec,job,list(path=output,method="fixture",widen_cells=0L))
  expect_identical(result$result$source_edition,"dem1")
  expect_identical(result$result$cutline_revision,rec$id)
  expect_true(file.exists(file.path(rec$path,"result","provenance.json")))
  expect_true(file.exists(file.path(rec$path,result$result$file)))
  next_rec <- store$hydro_save("study","event","stream","dem1",lines,rec$id,context)
  stage <- store$hydro_prepare(next_rec)
  newer <- store$hydro_save("study","event","stream","dem1",lines,next_rec$id,context)
  expect_error(store$hydro_publish(next_rec,stage,list()),"Inputs changed")
  expect_null(newer$result)
  expect_true(file.exists(file.path(rec$path,"result","hydro-dem.tif")))
})
