test_that("one visible task selector replaces competing action buttons and disclosures", {
  html <- as.character(mod_boundary_ui("test",study=list(boundary=TRUE)))
  expect_match(html,"Working on",fixed=TRUE)
  expect_match(html,'value="view" checked',fixed=TRUE)
  expect_false(grepl('id="test-edit_boundary"',html,fixed=TRUE))
  expect_false(grepl('id="test-define_stream"',html,fixed=TRUE))
  expect_false(grepl("Map and coordinate information",html,fixed=TRUE))
  expect_equal(boundary_initial_target(list(boundary=TRUE),FALSE,NULL),"view")
})

test_that("Workspace New leaves saved study intact and confirms discarding work", {
  store <- local_study_store(withr::local_tempdir())
  shiny::testServer(mod_study_server,args=list(store=store),{
    session$flushReact()
    session$setInputs(workspace_task="new",name="First",create=1)
    saved <- current()
    expect_false(grepl("Saved record details|Start another study",output$summary$html))
    session$setInputs(workspace_task="open")
    module_env <- environment(refresh)
    old <- get("editor",module_env); old$has_unsaved <- function() TRUE
    assign("editor",old,module_env)
    session$setInputs(workspace_task="new")
    expect_equal(current()$key,saved$key)
    session$setInputs(confirm_new=1)
    expect_null(current())
    expect_equal(store$read(saved$key)$study_id,saved$study_id)
    session$setInputs(name="Second",create=2)
    expect_equal(current()$name,"Second")
    expect_length(store$catalog()$choices,2)
  })
})

test_that("Stream task explains discovery and selection and preserves candidates", {
  store <- local_study_store(withr::local_tempdir())
  study <- store$create("Study")
  study <- store$save_boundary(study$key,stream_test_parent(),study$path)
  shiny::testServer(mod_boundary_server,args=list(study=study,store=store,
    is_active=function() TRUE,on_saved=function(x) NULL),{
    session$flushReact()
    session$setInputs(selection_target="stream",boundary_method="explore",map_mode="explore",stream_action="point")
    expect_match(output$workflow_next$html,"Click near a blue channel",fixed=TRUE)
    # A completed service result provides a pool; no remote dependency.
    exploring$result(stream_test_context()); session$flushReact()
    session$setInputs(stream_action="select")
    expect_match(output$workflow_next$html,"Check channel segments",fixed=TRUE)
    expect_match(output$workflow_next$html,"click an empty map location",fixed=TRUE)
    expect_match(output$select_upstream$html,"checkbox",fixed=TRUE)
    expect_match(output$select_upstream$html,"open",fixed=TRUE)
    session$setInputs(lines_upstream="c101")
    expect_match(output$workflow_next$html,"Enter the Stream name",fixed=TRUE)
    session$setInputs(stream_name="Creek",buffer_distance=100,buffer_unit="m")
    expect_match(output$workflow_next$html,"Select Preview Stream",fixed=TRUE)
    session$setInputs(preview_stream=1)
    expect_match(output$workflow_next$html,"Select Save Stream",fixed=TRUE)
    real_containment <- fluvgeo::check_study_area_containment
    testthat::with_mocked_bindings({
      session$setInputs(preview_stream=2)
      expect_match(output$stream_status$html,"Preview failed containment",fixed=TRUE)
      expect_match(output$workflow_next$html,"save is blocked",fixed=TRUE)
    }, check_study_area_containment=function(...) data.frame(status="outside"),.package="fluvgeo")
    expect_identical(fluvgeo::check_study_area_containment,real_containment)
    session$setInputs(preview_stream=3)
    expect_equal(stream_selection$preview()$containment,"inside")
    session$setInputs(selection_target="boundary",boundary_method="explore")
    expect_equal(stream_selection$selected(),"c101")
    dirty(TRUE)
    session$setInputs(selection_target="stream")
    expect_match(output$task_status$html,"Finish and save",fixed=TRUE)
    session$setInputs(selection_target="boundary",boundary_method="draw",map_mode="draw")
    expect_match(output$task_status$html,"Finish and save",fixed=TRUE)
  })
})
