test_that("reload opens the latest disk revision with both references and restores form definitions", {
  root <- withr::local_tempdir()
  store <- local_study_store(root)
  x <- store$create("Reload fixture")
  boundary <- sf::st_sf(geometry=sf::st_as_sfc(sf::st_bbox(c(xmin=-94,ymin=41,xmax=-93.9,ymax=41.1),crs=4326)))
  x <- store$save_boundary(x$key,boundary,x$path)
  x <- store$set_analysis_crs(x$key,"6344","Fixture","Fixture",x$path)
  spec <- fluvgeo::validate_study_vertical_reference("vertical_crs","5703","orthometric","metre")
  x <- store$set_vertical_reference(x$key,spec,x$path)
  hashes <- tools::md5sum(list.files(file.path(root,x$key),full.names=TRUE,pattern="gpkg$"))
  reload_session <- shiny::MockShinySession$new()
  reload_session$clientData <- list(url_search=paste0("?view=local&study=",x$key))
  updates <- list(); queries <- list()
  reload_session$sendInputMessage <- function(inputId,message) updates[[length(updates)+1L]] <<- list(id=inputId,message=message)
  reload_session$updateQueryString <- function(queryString,mode) queries[[length(queries)+1L]] <<- list(query=queryString,mode=mode)
  shiny::testServer(mod_study_server,args=list(store=local_study_store(root)),session=reload_session,{
    session$setInputs(workspace_task="new")
    expect_equal(current()$analysis_crs$epsg,6344)
    expect_identical(current()$vertical_reference,spec)
    expect_identical(current()$path,x$path)
    definitions <- vapply(Filter(function(x) x$id=="definition",updates),function(x) x$message$value,character(1))
    expect_true(all(c("EPSG:6344","EPSG:5703") %in% definitions))
    modes <- Filter(function(x) x$id=="mode",updates)
    expect_equal(tail(modes,1)[[1]]$message$value,"advanced")
    expect_equal(tail(queries,1)[[1]]$mode,"replace")
    expect_equal(shiny::parseQueryString(tail(queries,1)[[1]]$query)$study,x$key)
    # New is explicit; its URL must no longer cause the old study to reopen.
    session$setInputs(workspace_task="open")
    session$setInputs(workspace_task="new")
    expect_null(current())
    expect_equal(tail(queries,1)[[1]]$query,"?view=local")
  })
  expect_identical(tools::md5sum(names(hashes)),hashes)
})

test_that("invalid reload keys do not open a path or mutate saved studies", {
  store <- local_study_store(withr::local_tempdir()); x <- store$create("Retained")
  reload_session <- shiny::MockShinySession$new()
  reload_session$clientData <- list(url_search="?study=../../outside")
  shiny::testServer(mod_study_server,args=list(store=store),session=reload_session,{
    session$flushReact()
    expect_null(current())
    expect_equal(notice()$kind,"danger")
    expect_identical(store$read(x$key),x)
  })
})
